# Computation of matrix determinant (special case)

$$M = D + uv^T$$

$D$ - diagonal, $u,v$ - vectors.

We would like to compute determinant of $M$

## Schur complement and its use

![schur](https://wikimedia.org/api/rest_v1/media/math/render/svg/58a13e28c3c997eef24f6a5da0079deade54f087)

$$det(M) = det\begin{pmatrix}A & B \\ 0 & D\end{pmatrix} = det(A)det(D)$$

$$det(M) = det(A)det(D - CA^{-1}B) = det(D)det(A - B D^{-1}C)$$

## How to use this property
$$det(M) = det\begin{pmatrix}I_n & B \\ C & I_m\end{pmatrix} = det(I_m - CB) = det(I_n - BC)$$

Suppose $B,C$ - column and row: $B = u$, $C = v^T$

$$det(M) = det(I_n + uv^T) = det(I_1 + v^Tu) = 1 + v^Tu$$

$$det(D + uv^T) = det(D(I + D^{-1}uv^T)) = det(D)(1 + v^TD^{-1}u)$$

In [ ]:
def solve_2(a,b,c):
  D = b**2 - 4 * a * c
  return 1/(2*a)*(-b + np.sqrt(D)), 1/(2*a)*(-b - np.sqrt(D))

In [ ]:
def devide_and_conquer(A):
  n = A.shape[0]
  if n == 1:
    return A[0]
  else:
    n_sub = n // 2
    D1 = devide_and_conquer(A[:n_sub,:n_sub])
    D2 = devide_and_conquer(A[n_sub:,n_sub:])
    b = A[n_sub,n_sub-1]
    D1[-1] -= b
    D2[0] -= b
    l1,l2 = solve_2(1,-(D1[-1]+D2[0]+2*b),D1[-1]*D2[0] + b * (D1[-1]+D2[0]))
    D1[-1] = min(l1,l2)
    D2[0] = max(l1,l2)
    return np.concatenate([D1,D2])

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2.,1.,0.,0.],[1.,3.,1.,0.],[0.,1.,4.,1.],[0.,0.,1.,5.]])
A

array([[2., 1., 0., 0.],
       [1., 3., 1., 0.],
       [0., 1., 4., 1.],
       [0., 0., 1., 5.]])

In [ ]:
np.linalg.eigh(A)[0]

array([1.25471876, 2.82271708, 4.17728292, 5.74528124])

In [ ]:
devide_and_conquer(A)

array([1.38196601, 2.49305808, 4.50694192, 5.61803399])